name: easylayout
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-essentials
  - r-usethis
  - r-roxygen2
  - r-testthat
  - r-knitr
  - r-languageserver
  - r-rmarkdown
  - radian
  - pnpm
