import forceLayoutViva from "./forceLayoutViva";
import forceLayoutD3 from "./forceLayoutD3";

const layoutSettings = [
  {
    "value": "viva",
    "name": "@anvaka/VivaGraphJS",
    "spec": forceLayoutViva,
    "settings": [
      {
        "id": "springLength",
        "name": "Spring length",
        "type": "range",
        "min": 1,
        "max": 100,
        "step": 1,
        "value": 100,
        "shown": true,
      },
      {
        "id": "springCoeff",
        "name": "Spring coefficient",
        "type": "range",
        "min": 0.0001,
        "max": 0.0025,
        "step": 0.00001,
        "value": 0.0002,
        "shown": true,
      },
      {
        "id": "dragCoeff",
        "name": "Drag coefficient",
        "type": "range",
        "min": 0.01,
        "max": 1,
        "step": 0.01,
        "value": 0.01,
        "shown": true,
      },
      {
        "id": "gravity", // TODO: not updating during runtime
        "name": "Gravity",
        "type": "range",
        "min": -2,
        "max": -0.1,
        "step": 0.1,
        "value": -0.2,
        "shown": false,
      },
      {
        "id": "theta", // TODO: not updating during runtime
        "name": "Theta",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "value": 0.8,
        "shown": false,
      },
      {
        "id": "timeStep",
        "name": "Time step",
        "type": "range",
        "min": 1,
        "max": 100,
        "step": 1,
        "value": 10,
        "shown": true,
      },
    ],
  },
  {
    "value": "d3",
    "name": "@d3/d3-force",
    "spec": forceLayoutD3,
    "settings": [
      {
        "id": "alphaDecay",
        "name": "Temperature decay",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.001,
        "value": 0.0228,
        "shown": false,
      },
      {
        "id": "velocityDecay",
        "name": "Velocity decay",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "value": 0.4,
        "shown": false,
      },
      {
        "id": "chargeStrength",
        "name": "Node attraction",
        "type": "range",
        "min": -200,
        "max": 50,
        "step": 0.1,
        "value": -30,
      },
      {
        "id": "theta",
        "name": "Barnes–Hut approximation criterion",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.1,
        "value": 0.8,
        "shown": false,
      },
      {
        "id": "distanceMin",
        "name": "distanceMin",
        "type": "range",
        "min": 1,
        "max": 50,
        "step": 1,
        "value": 1,
        "shown": true,
      },
      {
        "id": "distanceMax",
        "name": "distanceMax",
        "type": "range",
        "min": 1,
        "max": 2000,
        "step": 1,
        "value": 2000,
        "shown": true,
      },
      {
        "id": "linkDistance",
        "name": "Link distance",
        "type": "range",
        "min": 0,
        "max": 100,
        "step": 1,
        "value": 30,
        "shown": true,
      },
      {
        "id": "linkStrength",
        "name": "Link distance",
        "type": "range",
        "min": 0,
        "max": 100,
        "step": 1,
        "value": 30,
        "shown": false,
      },
      {
        "id": "linkIterations",
        "name": "Link rigidity",
        "type": "range",
        "min": 1,
        "max": 10,
        "step": 1,
        "value": 1,
        "shown": true,
      },{
        "id": "centerX",
        "name": "Center X",
        "type": "range",
        "min": -1000,  // Adjust min/max based on your visualization needs
        "max": 1000,
        "step": 10,
        "value": 0.5,
        "shown": false,
      },
      {
        "id": "centerY",
        "name": "Center Y",
        "type": "range",
        "min": -1000,
        "max": 1000,
        "step": 10,
        "value": 0.5,
        "shown": false,
      },
      {
        "id": "centerStrength",
        "name": "Center strength",
        "type": "range",
        "min": -1000,
        "max": 1000,
        "step": 10,
        "value": 1,
        "shown": false,
      },
      {
        "id": "collisionRadius",
        "name": "Collision Radius",
        "type": "range",
        "min": 1,
        "max": 100,
        "step": 1,
        "value": 1,
        "shown": true,
      },
      {
        "id": "collisionStrength",
        "name": "Collision Strength",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "value": 0.7,
        "shown": true,
      },
      {
        "id": "x",
        "name": "Target X",
        "type": "range",
        "min": -1000, 
        "max": 1000,
        "step": 10,
        "value": 0.5,
        "shown": false,
      },
      {
        "id": "y",
        "name": "Target Y",
        "type": "range",
        "min": -1000,
        "max": 1000,
        "step": 10,
        "value": 0.5,
        "shown": false,
      },
      {
        "id": "xStrength",
        "name": "Strength towards Target X",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "value": 0.1,
        "shown": false,
      },
      {
        "id": "yStrength",
        "name": "Strength towards Target Y",
        "type": "range",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "value": 0.1,
        "shown": false,
      },
    ],
  },
  {
    "value": "cosmo",
    "name": "@cosmograph-org/cosmo",
    "spec": null,
    "settings": [
      {
        "id": "simulationRepulsion",
        "name": "Repulsion force coefficient",
        "type": "range",
        "min": 0.0,
        "max": 2.0,
        "step": 0.1,
        "value": 0.1,
        "shown": true,
      },
      {
        "id": "simulationRepulsionTheta",
        "name": "Barnes–Hut theta",
        "type": "range",
        "min": 0.3,
        "max": 2.0,
        "step": 0.1,
        "value": 1.7,
        "shown": true,
      },
      {
        "id": "repulsionQuadtreeLevels",
        "name": "Barnes–Hut approximation depth",
        "type": "range",
        "min": 5,
        "max": 12,
        "step": 1,
        "value": 12,
        "shown": false,
      },
      {
        "id": "simulationLinkSpring",
        "name": "Spring coefficient",
        "type": "range",
        "min": 0.0,
        "max": 2.0,
        "step": 0.01,
        "value": 1.0,
        "shown": true,
      },
      {
        "id": "simulationLinkDistance",
        "name": "Minimum link distance",
        "type": "range",
        "min": 1,
        "max": 20,
        "step": 1,
        "value": 2,
        "shown": true,
      },
      {
        "id": "simulationGravity",
        "name": "Gravity coefficient",
        "type": "range",
        "min": 0.0,
        "max": 1.0,
        "step": 0.01,
        "value": 0.0,
        "shown": true,
      },
      {
        "id": "simulationCenter",
        "name": "Centering force coefficient",
        "type": "range",
        "min": 0.0,
        "max": 1.0,
        "step": 0.01,
        "value": 0.0,
        "shown": true,
      },
      {
        "id": "simulationFriction",
        "name": "Friction coefficient",
        "type": "range",
        "min": 0.8,
        "max": 1.0,
        "step": 0.01,
        "value": 0.85,
        "shown": true,
      },
      {
        "id": "simulationDecay",
        "name": "Force simulation decay coefficient",
        "type": "range",
        "min": 100,
        "max": 10000,
        "step": 100,
        "value": 10000,
        "shown": true,
      },
      {
        "id": "repulsionFromMouse",
        "name": "Repulsion from the mouse pointer force coefficient",
        "type": "range",
        "min": 0.0,
        "max": 5.0,
        "step": 0.1,
        "value": 2.0,
        "shown": false,
      },
    ]
  },
]

export default layoutSettings;